"""add prompt response provider complexity to usage_logs

Revision ID: 67b65d3a8da3
Revises: 
Create Date: 2026-06-04 10:27:22.977304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b65d3a8da3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('prompt', sa.Text(), nullable=True))
    op.add_column('usage_logs', sa.Column('response', sa.Text(), nullable=True))
    op.add_column('usage_logs', sa.Column('provider', sa.String(length=100), nullable=True))
    op.add_column('usage_logs', sa.Column('complexity', sa.String(length=20), nullable=True))

    op.execute("UPDATE usage_logs SET prompt = '' WHERE prompt IS NULL")
    op.execute("UPDATE usage_logs SET response = '' WHERE response IS NULL")
    op.execute("UPDATE usage_logs SET provider = 'unknown' WHERE provider IS NULL")
    op.execute("UPDATE usage_logs SET complexity = 'medium' WHERE complexity IS NULL")

    op.alter_column('usage_logs', 'prompt', nullable=False)
    op.alter_column('usage_logs', 'response', nullable=False)
    op.alter_column('usage_logs', 'provider', nullable=False)
    op.alter_column('usage_logs', 'complexity', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_logs', 'complexity')
    op.drop_column('usage_logs', 'provider')
    op.drop_column('usage_logs', 'response')
    op.drop_column('usage_logs', 'prompt')
    # ### end Alembic commands ###
