"""make fk nullable in usage_logs

Revision ID: 6de7c13066e0
Revises: 67b65d3a8da3
Create Date: 2026-06-04 17:46:41.575274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de7c13066e0'
down_revision: Union[str, Sequence[str], None] = '67b65d3a8da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
